export type TRandomIcon =
   | "JavaScript"
   | "TypeScript"
   | "HTML"
   | "CSS"
   | "React"
   | "NodeJs"
   | "Python"
   | "Java"
   | "ExpressJs"
   | "C"
   | "MongoDB"
   | "Github"
   | "Linkedin"
   | "Twitter"
   | "Git"
   | "NextJs"
   | "VSCode"
   | "Apache Atlas"
   | "Apache Spark"
   | "Apache Airflow"
   | "Docker"
   | "SQL";
